-- FraudX Supabase PostgreSQL schema.
-- Run this once in the Supabase SQL Editor before starting FastAPI.

create table if not exists accounts (
    id bigint generated by default as identity primary key,
    account_id text not null unique,
    name text not null,
    email text,
    phone text,
    location text,
    device_id text,
    ip_address text,
    account_status text not null default 'ACTIVE',
    risk_score double precision not null default 0,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists fraud_rings (
    id bigint generated by default as identity primary key,
    ring_id text not null unique,
    name text,
    risk_score double precision not null default 0,
    severity text not null default 'LOW',
    account_count integer not null default 0,
    transaction_count integer not null default 0,
    total_amount double precision not null default 0,
    pattern_type text not null,
    status text not null default 'Active',
    detected_at timestamptz not null default timezone('utc', now())
);

create table if not exists transactions (
    id bigint generated by default as identity primary key,
    transaction_id text not null unique,
    sender_account_id text not null references accounts(account_id),
    receiver_account_id text not null references accounts(account_id),
    amount double precision not null,
    currency text not null default 'INR',
    timestamp timestamptz not null default timezone('utc', now()),
    location text,
    device_id text,
    ip_address text,
    transaction_type text not null default 'transfer',
    status text not null default 'NORMAL',
    risk_score double precision not null default 0,
    risk_level text not null default 'LOW',
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists agents (
    id bigint generated by default as identity primary key,
    agent_id text not null unique,
    name text not null,
    agent_type text not null,
    status text not null default 'Active',
    description text,
    tasks_completed integer not null default 0,
    items_analyzed integer not null default 0,
    last_activity timestamptz not null default timezone('utc', now())
);

create table if not exists investigations (
    id bigint generated by default as identity primary key,
    investigation_id text not null unique,
    target_account_id text not null references accounts(account_id),
    fraud_ring_id text references fraud_rings(ring_id),
    risk_score double precision not null default 0,
    status text not null default 'RUNNING',
    summary text,
    confidence double precision not null default 0,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists fraud_ring_members (
    id bigint generated by default as identity primary key,
    ring_id text not null references fraud_rings(ring_id) on delete cascade,
    account_id text not null references accounts(account_id) on delete cascade,
    role text,
    risk_score double precision not null default 0,
    created_at timestamptz not null default timezone('utc', now()),
    unique (ring_id, account_id)
);

create table if not exists fraud_ring_edges (
    id bigint generated by default as identity primary key,
    ring_id text not null references fraud_rings(ring_id) on delete cascade,
    source_account_id text not null references accounts(account_id) on delete cascade,
    target_account_id text not null references accounts(account_id) on delete cascade,
    transaction_count integer not null default 0,
    total_amount double precision not null default 0,
    created_at timestamptz not null default timezone('utc', now()),
    unique (ring_id, source_account_id, target_account_id)
);

create table if not exists investigation_evidence (
    id bigint generated by default as identity primary key,
    evidence_id text not null unique,
    investigation_id text not null references investigations(investigation_id) on delete cascade,
    category text not null,
    description text not null,
    severity text not null default 'INFO',
    confidence double precision not null default 0,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists investigation_events (
    id bigint generated by default as identity primary key,
    investigation_id text not null references investigations(investigation_id) on delete cascade,
    event_type text not null,
    description text not null,
    status text not null default 'completed',
    occurred_at timestamptz not null default timezone('utc', now())
);

create table if not exists countermeasures (
    id bigint generated by default as identity primary key,
    action_id text not null unique,
    account_id text not null references accounts(account_id),
    investigation_id text references investigations(investigation_id),
    action_type text not null,
    reason text,
    risk_score double precision not null default 0,
    status text not null default 'Pending Approval',
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists agent_activity (
    id bigint generated by default as identity primary key,
    agent_id text references agents(agent_id) on delete set null,
    investigation_id text references investigations(investigation_id) on delete set null,
    agent_name text not null,
    action text not null,
    target text,
    status text not null,
    icon text,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists notifications (
    id bigint generated by default as identity primary key,
    notification_id text not null unique,
    title text not null,
    message text,
    severity text not null default 'INFO',
    read boolean not null default false,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists reports (
    id bigint generated by default as identity primary key,
    report_id text not null unique,
    investigation_id text not null references investigations(investigation_id),
    report_type text not null default 'FRAUD_INVESTIGATION',
    title text not null,
    summary text,
    risk_score double precision not null default 0,
    confidence double precision not null default 0,
    content jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists simulation_runs (
    id bigint generated by default as identity primary key,
    run_id text not null unique,
    target_account_id text not null references accounts(account_id),
    investigation_id text,
    status text not null default 'STARTED',
    risk_score double precision,
    started_at timestamptz not null default timezone('utc', now()),
    completed_at timestamptz
);

create index if not exists idx_transactions_sender on transactions(sender_account_id);
create index if not exists idx_transactions_receiver on transactions(receiver_account_id);
create index if not exists idx_transactions_timestamp on transactions(timestamp desc);
create index if not exists idx_investigations_target on investigations(target_account_id);
create index if not exists idx_activity_created_at on agent_activity(created_at desc);
create index if not exists idx_events_investigation on investigation_events(investigation_id, occurred_at);
create index if not exists idx_evidence_investigation on investigation_evidence(investigation_id);

-- The backend uses the service-role key server-side and does not expose these tables to React.
-- Enable RLS if the project will later be accessed directly by authenticated clients.
