import React from 'react';
import { useNavigate } from 'react-router-dom';
import { FileText, Plus, Eye, Clock, CheckCircle2, TrendingUp, AlertTriangle } from 'lucide-react';

import PageHeader from '../components/common/PageHeader';
import StatCard from '../components/common/StatCard';
import RiskBadge from '../components/common/RiskBadge';
import StatusBadge from '../components/common/StatusBadge';
import { useSimulation } from '../context/SimulationContext';
import { formatDate } from '../utils/formatters';

export default function Reports() {
  const { reports, setReports, showToast } = useSimulation();
  const navigate = useNavigate();

  const handleGenerateReport = () => {
    // Generate new mock report
    const newId = `RPT-${Math.floor(Math.random() * 900) + 100}`;
    const newReport = {
      id: newId,
      investigation: 'INV-1027',
      type: 'Fraud Investigation',
      riskScore: 72,
      generatedBy: 'Forensic Report Agent',
      date: new Date().toISOString(),
      status: 'Ready',
      title: `Generated Investigation Report: ${newId}`,
      sections: {
        executiveSummary: 'This report was generated via the dynamic generator tool, mapping convergent source transfer cycles on the collection accounts.',
        riskAssessment: 'Risk Score: 72/100 (HIGH). Composite risk based on multi-account funneling behaviors.',
        fraudRingAnalysis: 'Converging topology directed to collector nodes.',
        transactionEvidence: 'Transaction streams verified.',
        connectedAccounts: 'Participant logs attached.',
        agentFindings: 'Forensic report compiled successfully.',
        recommendedCountermeasures: 'Escalate to investigation team.',
        investigationTimeline: 'Mapped sequence.',
        confidenceScore: 84,
      },
    };

    setReports(prev => [newReport, ...prev]);
    showToast(`Forensic Report ${newId} compiled successfully`, 'success');
  };

  const readyCount = reports.filter(r => r.status === 'Ready' || r.status === 'Completed').length;
  const pendingCount = reports.filter(r => r.status === 'Pending').length;

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <PageHeader
        title="Report Center"
        subtitle="Access compiled forensic files generated by reporting agents"
      >
        <button
          onClick={handleGenerateReport}
          className="flex items-center gap-1.5 px-4 py-2 text-sm font-semibold text-white bg-accent-blue hover:bg-accent-blue/90 rounded-lg transition-colors shadow-lg shadow-accent-blue/15"
        >
          <Plus className="w-4 h-4" />
          <span>Generate Report</span>
        </button>
      </PageHeader>

      {/* Report KPIs */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          title="Generated Reports"
          value={readyCount}
          subtitle="Available for export"
          icon={FileText}
          trend="up"
          color="#3b82f6"
        />
        <StatCard
          title="Pending Reports"
          value={pendingCount}
          subtitle="In pipeline"
          icon={Clock}
          trend="down"
          color="#f59e0b"
        />
        <StatCard
          title="Critical Audits"
          value={reports.filter(r => r.riskScore >= 80).length}
          subtitle="Score above 80"
          icon={AlertTriangle}
          trend="up"
          color="#ef4444"
        />
        <StatCard
          title="Reports This Month"
          value={14}
          subtitle="Generated dynamically"
          icon={TrendingUp}
          trend="up"
          color="#22c55e"
        />
      </div>

      {/* Reports Table list */}
      <div className="bg-surface-800 border border-surface-600/50 rounded-xl p-5">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-sm font-bold text-white uppercase tracking-wider">Forensic Reports Ledger</h2>
            <p className="text-xs text-surface-200 mt-0.5">Click rows to open compiled file and view findings</p>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="border-b border-surface-700 text-surface-300 font-semibold bg-surface-700/10">
                <th className="py-3 px-4">Report ID</th>
                <th className="py-3 px-4">Investigation ID</th>
                <th className="py-3 px-4">Report Type</th>
                <th className="py-3 px-4">Target Risk</th>
                <th className="py-3 px-4">Compiled By</th>
                <th className="py-3 px-4">Date Generated</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-surface-700/50 text-white font-medium">
              {reports.map((rpt) => (
                <tr
                  key={rpt.id}
                  onClick={() => rpt.status !== 'Pending' && navigate(`/reports/${rpt.id}`)}
                  className={`transition-colors ${
                    rpt.status === 'Pending'
                      ? 'opacity-65 cursor-not-allowed'
                      : 'hover:bg-surface-700/20 cursor-pointer'
                  }`}
                >
                  <td className="py-3.5 px-4 font-mono font-bold text-accent-cyan">{rpt.id}</td>
                  <td className="py-3.5 px-4 font-mono">{rpt.investigation}</td>
                  <td className="py-3.5 px-4 text-surface-200">{rpt.type}</td>
                  <td className="py-3.5 px-4">
                    <RiskBadge score={rpt.riskScore} />
                  </td>
                  <td className="py-3.5 px-4 text-surface-300">{rpt.generatedBy}</td>
                  <td className="py-3.5 px-4 font-mono text-surface-300">
                    {formatDate(rpt.date)}
                  </td>
                  <td className="py-3.5 px-4">
                    <StatusBadge status={rpt.status} />
                  </td>
                  <td className="py-3.5 px-4 text-right">
                    <button
                      disabled={rpt.status === 'Pending'}
                      className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-surface-700 hover:bg-surface-600 disabled:opacity-50 transition-colors"
                    >
                      <Eye className="w-3.5 h-3.5" />
                      <span>View</span>
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
